default: &default
  project_id: luft-184208
  oauth2:
    client_id: 277647672180-u0k36jj1f0ejab3obko9i8oje15u9dl4.apps.googleusercontent.com
    client_secret: r3F6Ht0q57PL2nQoAnc0AsJV
  cloud_storage:
    bucket: luft
    access_key_id: GOOGDRRLGDJJHPXZFM2H
    secret_access_key: Nz3d9UXL20M/9p3sV5EJoJeejC4NdPBbOVMztLLM 

development:
  <<: *default

production:
  <<: *default